# Generated by Django 5.1 on 2024-10-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_modelwebsitesetup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelMenuLink',
            new_name='MenuLinkModel',
        ),
        migrations.RenameModel(
            old_name='ModelWebsiteSetup',
            new_name='WebsiteSetupModel',
        ),
        migrations.AlterModelOptions(
            name='menulinkmodel',
            options={'verbose_name': 'Menu link', 'verbose_name_plural': 'Menu links'},
        ),
        migrations.AlterModelOptions(
            name='websitesetupmodel',
            options={'verbose_name': 'Website setup', 'verbose_name_plural': 'Website setups'},
        ),
    ]
