# Generated by Django 5.1 on 2024-10-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_modelmenulink_menulinkmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulinkmodel',
            name='website_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.websitesetupmodel'),
        ),
    ]
