# Generated by Django 5.1 on 2024-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_menulinkmodel_website_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetupmodel',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%y/%m'),
        ),
    ]
