# Generated by Django 5.1 on 2024-10-16 18:25

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_websitesetupmodel_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetupmodel',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%y/%m', validators=[utils.model_validators.validate_image]),
        ),
    ]
